direction: down

title: { 
  label: custom-display-names
  class: diagram-title
}

root-task: {
  label: "Root(3)"
  class: computed
}
leaf0: {
  label: "Leaf Nr. 0"
  class: computed
}
root-task -> leaf0: {class: subtask-edge}
leaf1: {
  label: "Leaf Nr. 1"
  class: computed
}
root-task -> leaf1: {class: subtask-edge}
leaf2: {
  label: "Leaf Nr. 2"
  class: computed
}
root-task -> leaf2: {class: subtask-edge}
