direction: down

title: { 
  label: larger-job
  class: diagram-title
}

my-task: {
  label: "MyTask"
  class: computed
}
subtask1: {
  label: "SubTask"
  class: computed
}
my-task -> subtask1: {class: subtask-edge}
subtask2: {
  label: "SubTask"
  class: running
}
my-task -> subtask2: {class: subtask-edge}
subtask3: {
  label: "SubTask"
  class: computed
}
my-task -> subtask3: {class: subtask-edge}

dependent-task1: {
  label: "DependentTask"
  class: running
}
subtask1 -> dependent-task1: {class: subtask-edge}
leaf-task1: {
  label: "LeafTask"
  class: computed
}
subtask1 -> leaf-task1: {class: subtask-edge}
leaf-task1 <- dependent-task1: {class: dependency-edge}

dependent-task2: {
  label: "DependentTask"
  class: queued
}
subtask3 -> dependent-task2: {class: subtask-edge}
leaf-task2: {
  label: "LeafTask"
  class: running
}
subtask3 -> leaf-task2: {class: subtask-edge}
leaf-task2 <- dependent-task2: {class: dependency-edge}
