direction: down

title: { 
  label: task-states
  class: diagram-title
}

my-task: {
  label: "ComputedRootTask"
  class: computed
}
queued-task: {
  label: "QueuedTask"
  class: queued
}
my-task -> queued-task: {class: subtask-edge}
running-task: {
  label: "RunningTask"
  class: running
}
my-task -> running-task: {class: subtask-edge}
computed-task: {
  label: "ComputedTask"
  class: computed
}
my-task -> computed-task: {class: subtask-edge}
computed-task-child: {
  label: "RunningLeafTask"
  class: running
}
computed-task -> computed-task-child: {class: subtask-edge}
completed-task: {
  label: "CompletedTask"
  class: computed
}
my-task -> completed-task: {class: subtask-edge}
completed-task-child: {
  label: "CompletedLeafTask"
  class: computed
}
completed-task -> completed-task-child: {class: subtask-edge}

failed-task: {
  label: "FailedTask"
  class: failed
}
my-task -> failed-task: {class: subtask-edge}
